on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize # a commit on the head branch of the PR

jobs:
  comment:
    permissions:
      pull-requests: write
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - name: Comment with labels
        id: get-labels
        uses: actions/github-script@v7
        with:
          script: |
            /* Grab labels on issue/pull request */
            const result = github.rest.issues.listLabelsOnIssue({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            
            /* use "then" to grab response */
            result.then(function(result) {
              /* Run over each label in the data array of the result */
              let labels = Array.from(result['data'], (label) => label['name'])
              console.log(`pull_request_labels=[${labels}] >> $GITHUB_OUTPUT`)

              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `Deploying to ${labels.join(' and ')}`
              })
            })
      - name: use labels
        run: |
          echo "${{steps.get-labels.outputs.result}}"
          echo "${{steps.get-labels.outputs.labels}}"

