on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize # a commit on the head branch of the PR

jobs:
  comment:
    permissions:
      pull-requests: write
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v7
        with:
          script: console.log(context)
      # - name: Get labels
      #   run: |
      #     gh api --jq '.labels.[].name' /repos/{owner}/{repo}/pulls/${{ github.event.number }}
      - name: get labels 2
        uses: actions/github-script@v7
        with:
          script: |
            /* initialize labels array */
            let labels = [] 

            /* Grab labels on issue/pull request */
            const result = github.rest.issues.listLabelsOnIssue({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            
            /* use "then" to grab response */
            result.then(function(result) {
              /* Run over each label in the data array of the result */
              result['data'].forEach(function(label) {
                /* Add label name to list of labels */
                labels.push(label['name'])
              })
            })

            const result = github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Deploying to ${labels.join(' and ')}`
            })