on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize # a commit on the head branch of the PR

env:
  SCRIPT_FOLDER: ${{ github.workspace }}/.github/scripts
  BUNDLE_TARGET: service_principal
  METADATA_FOLDER: _metadata
  BUNDLE_VALIDATION_FOLDER: validation_files
  NIGHTLY_FOLDER: nightly
  DEPENDENCIES_FOLDER: dependencies



jobs:
  comment_and_deploy:
    permissions:
      pull-requests: write
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    outputs:
      environments: ${{steps.get-labels.outputs.labels}}
      table_bundles: ${{ steps.get_bundles.outputs.table_bundles }}
      view_bundles: ${{ steps.get_bundles.outputs.view_bundles }}
      deploy_all: ${{steps.get-labels.outputs.deploy_all_changes}}
    steps:
      - name: Get labels and post comment
        id: get-labels
        uses: actions/github-script@v7
        with:
          script: |
            const deploy_all_label = 'deploy_all_changes'
          
            /* Grab labels on issue/pull request */
            const result = github.rest.issues.listLabelsOnIssue({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            
            result.then(function(result) {
              
              /* Grab label names from result */
              let labels = Array.from(result['data'], (label) => label['name'])

              /* Check if deploy_all label is set. Remove label if it is. */
              let deploy_all = labels.includes(deploy_all_label) 
              if (deploy_all) {
                core.setOutput(deploy_all_label, true)
                labels = labels.filter((label) => label != deploy_all_label )

                github.rest.issues.removeLabel({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: deploy_all_label
                })
              }
              
              /* Set GitHub outputs */
              core.setOutput('labels', labels)

              /* Prepare comment body */
              let body = ''
              if ('${{github.event.action}}' == 'synchronize') {
                body = 'You have committed to a pull request'

                if (deploy_all) {
                  body += ' and marked the action to deploy all changes'
                }
                body += '.\n'
              } else {
                body = 'You have ${{github.event.action}} a pull request.\n'
              }
              body += `Deploying to the following environments:\n- ${labels.join('\n- ')}`

              /* post comment body */
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
              })
            })
      - name: Pull repo to runner
        uses: actions/Checkout@v4
        with:
          fetch-depth: 0 #Fetch full history to allow for git diff before..after
          ref: ${{ github.event.pull_request.head.sha }}
  
      - run: |
          git config core.quotepath off # Allows for æ,ø,å in filepaths

      - name: (re)opened git diff
        if: github.event.action == 'reopened' || github.event.action == 'opened' || (github.event.action == 'synchronize' && steps.get-labels.outputs.deploy_all_changes == 'true')
        run: |
          git diff --name-status --merge-base origin/main > git_status.txt
          cat git_status.txt
      
      - name: commit git diff
        if: github.event.action == 'synchronize' && steps.get-labels.outputs.deploy_all_changes != 'true'
        run: |
          git diff --name-status ${{ github.event.before }}..${{ github.event.after }}  > git_status.txt
          cat git_status.txt

      # Note: first argument is name of input file, second is name of output file, third is the name of the environment folder
      - name: Identify added and modified bundles
        run: |
          python ${{ env.SCRIPT_FOLDER }}/bundles_from_git_status.py git_status.txt ./ "deployment" --ignore_case

      - name: Print bundles
        run: | 
          echo "Views:"
          cat view_bundles.json
          echo ""
          echo "Tables:"
          cat table_bundles.json

      # Lastly we write the list of changed bundles into the output of this step, with the name "changed_bundles".
      # Note, we must also specify an id to the step, to be able to use the output, just as before.
      - name: Write list of changed bundles to output
        id: get_bundles
        run: |
          echo "view_bundles=$(cat view_bundles.json)" >> "$GITHUB_OUTPUT"
          echo "table_bundles=$(cat table_bundles.json)" >> "$GITHUB_OUTPUT"

  deploy_all_tables:
    needs: comment_and_deploy
    uses: ./.github/workflows/deploy_tables.yml
    strategy:
      matrix:
        table_path: ${{fromJson(needs.comment_and_deploy.outputs.table_bundles)}}
        environment: ${{fromJson(needs.comment_and_deploy.outputs.environments)}}
    with:
      table_path: ${{matrix.table_path}}
      environment: ${{matrix.environment}}
